# Codecov configuration
# https://docs.codecov.io/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "80...100"

  status:
    # Overall project coverage
    project:
      default:
        target: 95%
        threshold: 2%  # Allow 2% drop from target
        if_ci_failed: error

    # Coverage of changed lines only (patch)
    patch:
      default:
        target: 90%  # Patch coverage target (new code)
        threshold: 5%  # Allow some flexibility for edge cases
        if_ci_failed: error

# Don't fail for missing coverage on these patterns
ignore:
  - "tests/**/*"
  - "**/__init__.py"

# Comment configuration
comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: true
